-- MySQL Script generated by MySQL Workbench
-- Mon May 20 19:11:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bgs_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bgs_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bgs_db` DEFAULT CHARACTER SET utf8 ;
USE `bgs_db` ;

-- -----------------------------------------------------
-- Table `bgs_db`.`dogadaji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgs_db`.`dogadaji` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(100) NOT NULL,
  `mjesto` VARCHAR(100) NOT NULL,
  `datum` DATETIME NOT NULL,
  `organizator` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

INSERT INTO `dogadaji` (`id`,`naziv`,`mjesto`,`datum`,`organizator`) 
  VALUES (1,'Star Wars Armada','Čakovec','2019-07-11','Jura Cilar');
INSERT INTO `dogadaji` (`id`,`naziv`,`mjesto`,`datum`,`organizator`) 
  VALUES (2,'XCOM The Board Game','Casa Latina','2019-07-22','Matteo Posavec');
  
commit;


-- -----------------------------------------------------
-- Table `bgs_db`.`korisnici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bgs_db`.`korisnici` (
  `id_korisnik` INT(11) NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(100) NOT NULL,
  `prezime` VARCHAR(100) NOT NULL,
  `spol` VARCHAR(1) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `datum_rodenja` DATE NOT NULL,
  PRIMARY KEY (`id_korisnik`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
